# Philippine National ID (PhilID) Template
# Version: 1.0.0
# Last Updated: 2025-01-14
# Description: Template for Philippine National ID issued by PSA

document:
  type: "PHILIPPINE_ID"
  name: "Philippine National ID"
  issuer: "Philippine Statistics Authority (PSA)"
  country: "PH"
  version: "2.0"  # Current PhilID version
  
  # Document dimensions (in mm)
  dimensions:
    width: 85.6
    height: 53.98
    aspect_ratio: 1.586
  
  # Document characteristics
  characteristics:
    material: "polycarbonate"
    color_scheme: ["blue", "white", "gold"]
    has_chip: false
    has_magnetic_strip: false
    has_barcode: true
    has_qr_code: true
    has_mrz: false
    has_hologram: true

# Field Definitions with ROI (Region of Interest)
# Coordinates are in percentage of document dimensions
fields:
  # Front side fields
  front:
    # Philippine Statistics Authority text
    header_text:
      roi:
        x: 10
        y: 5
        width: 80
        height: 10
      expected_text: "REPUBLIKA NG PILIPINAS"
      font: "Arial"
      font_size: 10
      validation:
        type: "exact_match"
        case_sensitive: false
    
    # PhilSys Number (PSN)
    psn:
      roi:
        x: 10
        y: 20
        width: 40
        height: 8
      field_name: "PhilSys Number"
      format: "XXXX-XXXX-XXXX-XXXX"
      validation:
        type: "regex"
        pattern: "^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$"
        checksum: "luhn"
      font: "OCR-B"
      font_size: 12
      required: true
    
    # Full Name
    full_name:
      roi:
        x: 10
        y: 30
        width: 60
        height: 10
      field_name: "Buong Pangalan / Full Name"
      subfields:
        last_name:
          roi:
            x: 10
            y: 30
            width: 60
            height: 5
        first_name:
          roi:
            x: 10
            y: 35
            width: 60
            height: 5
        middle_name:
          roi:
            x: 10
            y: 40
            width: 60
            height: 5
      validation:
        type: "alpha_with_spaces"
        min_length: 2
        max_length: 100
      font: "Arial Bold"
      font_size: 14
      required: true
    
    # Sex
    sex:
      roi:
        x: 10
        y: 45
        width: 20
        height: 5
      field_name: "Kasarian / Sex"
      values: ["M", "F", "MALE", "FEMALE", "LALAKI", "BABAE"]
      validation:
        type: "enum"
      font: "Arial"
      font_size: 11
      required: true
    
    # Date of Birth
    birth_date:
      roi:
        x: 35
        y: 45
        width: 25
        height: 5
      field_name: "Petsa ng Kapanganakan / Date of Birth"
      format: "DD/MM/YYYY"
      validation:
        type: "date"
        min_age: 0
        max_age: 150
      font: "Arial"
      font_size: 11
      required: true
    
    # Blood Type
    blood_type:
      roi:
        x: 65
        y: 45
        width: 15
        height: 5
      field_name: "Uri ng Dugo / Blood Type"
      values: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]
      validation:
        type: "enum"
      font: "Arial"
      font_size: 11
      required: false
    
    # Address
    address:
      roi:
        x: 10
        y: 52
        width: 70
        height: 12
      field_name: "Tirahan / Address"
      validation:
        type: "alphanumeric_with_special"
        min_length: 10
        max_length: 200
      font: "Arial"
      font_size: 10
      required: true
    
    # Photo
    photo:
      roi:
        x: 70
        y: 20
        width: 25
        height: 30
      field_name: "Photo"
      validation:
        type: "face_detection"
        min_face_size: [80, 80]
        max_faces: 1
      required: true
    
    # QR Code
    qr_code:
      roi:
        x: 75
        y: 55
        width: 20
        height: 20
      field_name: "QR Code"
      encoding: "alphanumeric"
      error_correction: "M"
      validation:
        type: "qr_code"
        verify_content: true
      required: true
    
    # Signature
    signature:
      roi:
        x: 10
        y: 70
        width: 30
        height: 10
      field_name: "Lagda / Signature"
      validation:
        type: "signature_detection"
        min_strokes: 2
      required: true
  
  # Back side fields
  back:
    # Card Number
    card_number:
      roi:
        x: 10
        y: 10
        width: 30
        height: 5
      field_name: "Card Number"
      format: "XXXXXXXXXX"
      validation:
        type: "alphanumeric"
        length: 10
      font: "OCR-B"
      font_size: 10
      required: true
    
    # Issue Date
    issue_date:
      roi:
        x: 10
        y: 20
        width: 25
        height: 5
      field_name: "Petsa ng Isyu / Date of Issue"
      format: "DD/MM/YYYY"
      validation:
        type: "date"
        max_future_days: 0
      font: "Arial"
      font_size: 10
      required: true
    
    # Expiry Date
    expiry_date:
      roi:
        x: 40
        y: 20
        width: 25
        height: 5
      field_name: "Petsa ng Expiry / Expiry Date"
      format: "DD/MM/YYYY"
      validation:
        type: "date"
        min_future_days: 0
      font: "Arial"
      font_size: 10
      required: true
    
    # Place of Birth
    birth_place:
      roi:
        x: 10
        y: 30
        width: 60
        height: 5
      field_name: "Lugar ng Kapanganakan / Place of Birth"
      validation:
        type: "alpha_with_spaces"
        min_length: 2
        max_length: 100
      font: "Arial"
      font_size: 10
      required: true
    
    # Marital Status
    marital_status:
      roi:
        x: 10
        y: 40
        width: 25
        height: 5
      field_name: "Katayuang Sibil / Marital Status"
      values: ["SINGLE", "MARRIED", "WIDOWED", "SEPARATED", "ANNULLED"]
      validation:
        type: "enum"
      font: "Arial"
      font_size: 10
      required: false

# Security Features
security_features:
  # Hologram
  hologram:
    location:
      x: 85
      y: 10
      width: 10
      height: 15
    type: "philippine_eagle"
    verification_method: "tilt_test"
    angles: [0, 45, 90]
  
  # UV Features
  uv_features:
    - location:
        x: 0
        y: 0
        width: 100
        height: 100
      pattern: "philippine_map"
      color: "green"
      wavelength: 365  # nm
    
    - location:
        x: 20
        y: 20
        width: 20
        height: 20
      pattern: "psa_logo"
      color: "blue"
      wavelength: 365
  
  # Microprinting
  microprinting:
    - location:
        x: 10
        y: 80
        width: 80
        height: 2
      text: "PHILIPPINESTATISTICSAUTHORITY"
      font_size: 0.5
      magnification_required: 10
  
  # Watermark
  watermark:
    location:
      x: 30
      y: 30
      width: 40
      height: 40
    pattern: "philippine_flag"
    visibility: "backlight"
  
  # Ghost Image
  ghost_image:
    location:
      x: 50
      y: 60
      width: 15
      height: 20
    type: "photo_replica"
    verification_method: "visual_comparison"
  
  # Security Thread
  security_thread:
    location:
      x: 50
      y: 0
      width: 2
      height: 100
    type: "embedded"
    color_shift: true
    text: "PSA"

# Validation Rules
validation_rules:
  # PSN Checksum
  psn_checksum:
    algorithm: "luhn_mod10"
    check_digit_position: 16
  
  # Date Consistency
  date_consistency:
    - rule: "birth_date < issue_date"
      error: "Birth date must be before issue date"
    
    - rule: "issue_date < expiry_date"
      error: "Issue date must be before expiry date"
    
    - rule: "expiry_date - issue_date = 5 years"
      error: "PhilID validity is 5 years"
  
  # Age Validation
  age_validation:
    min_age: 0
    max_age: 150
    compute_from: "birth_date"
  
  # Field Dependencies
  field_dependencies:
    - if_field: "marital_status"
      equals: "SINGLE"
      then_field: "age"
      must_be: ">= 18"

# OCR Settings
ocr_settings:
  # Language
  language: "eng+fil"  # English + Filipino
  
  # Preprocessing
  preprocessing:
    - "deskew"
    - "denoise"
    - "contrast_enhancement"
    - "binarization"
  
  # OCR Engine
  engine: "tesseract"
  oem: 3  # LSTM engine
  psm: 3  # Fully automatic page segmentation
  
  # Post-processing
  post_processing:
    - "spell_check"
    - "format_validation"
    - "field_mapping"

# Template Metadata
metadata:
  created_date: "2025-01-14"
  last_updated: "2025-01-14"
  version: "1.0.0"
  author: "KYC System"
  notes: "Philippine National ID template based on PSA specifications"
  
  # Supported versions
  supported_versions:
    - "1.0"  # Old format
    - "2.0"  # Current format
  
  # Known issues
  known_issues:
    - "QR code may be damaged in older cards"
    - "Hologram verification requires proper lighting"
    - "Some cards may have Filipino-only text"
